spring:
  application:
    name: url_monitor

  datasource:
    url: jdbc:postgresql://localhost:5432/uptime_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true